version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 10
    reviewers:
      - 'Penthious'
    assignees:
      - 'Penthious'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'automated'
    ignore:
      # Ignore major version updates for these packages
      - dependency-name: '@expo/vector-icons'
        update-types: ['version-update:semver-major']
      - dependency-name: 'expo'
        update-types: ['version-update:semver-major']
      - dependency-name: 'react'
        update-types: ['version-update:semver-major']
      - dependency-name: 'react-native'
        update-types: ['version-update:semver-major']
