import type { KingdomCatalog } from '@/models/kingdom';
import {
  DEVIL_OF_THE_SMELTED_FEARS_ID,
  EGGKNIGHT_ID,
  IRONCAST_DEAD_ID,
  KNIGHT_OF_THE_FEN_ID,
  PALEBLOOD_WORM_ID,
  PANZERDRAGON_VELDR_ID,
  PUMPKINHEAD_MONSTROSITIES_ID,
  PUPPET_KING_EDELHARDT_ID,
  RATWOLVES_ID,
  WINGED_NIGHTMARE_ID,
} from '@/catalogs/monsters';

export const POS_ID = 'principality-of-stone';
export const PRINCIPALITY_OF_STONE: KingdomCatalog = {
  id: POS_ID,
  name: 'Principality of Stone',
  bestiary: {
    monsters: [
      { id: RATWOLVES_ID },
      { id: WINGED_NIGHTMARE_ID },
      { id: PALEBLOOD_WORM_ID },
      { id: PUMPKINHEAD_MONSTROSITIES_ID },
      { id: KNIGHT_OF_THE_FEN_ID },
      { id: IRONCAST_DEAD_ID },
      { id: EGGKNIGHT_ID },
      { id: PUPPET_KING_EDELHARDT_ID },
      { id: DEVIL_OF_THE_SMELTED_FEARS_ID },
      { id: PANZERDRAGON_VELDR_ID },
    ],
    stages: [
      {
        [RATWOLVES_ID]: 1,
        [WINGED_NIGHTMARE_ID]: null,
        [PALEBLOOD_WORM_ID]: 1,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 1,
        [KNIGHT_OF_THE_FEN_ID]: null,
        [IRONCAST_DEAD_ID]: 1,
        [EGGKNIGHT_ID]: 1,
        [PUPPET_KING_EDELHARDT_ID]: null,
        [DEVIL_OF_THE_SMELTED_FEARS_ID]: null,
        [PANZERDRAGON_VELDR_ID]: null,
      },
      {
        [RATWOLVES_ID]: 1,
        [WINGED_NIGHTMARE_ID]: null,
        [PALEBLOOD_WORM_ID]: 1,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 1,
        [KNIGHT_OF_THE_FEN_ID]: 1,
        [IRONCAST_DEAD_ID]: 1,
        [EGGKNIGHT_ID]: 1,
        [PUPPET_KING_EDELHARDT_ID]: null,
        [DEVIL_OF_THE_SMELTED_FEARS_ID]: null,
        [PANZERDRAGON_VELDR_ID]: null,
      },
      {
        [RATWOLVES_ID]: 2,
        [WINGED_NIGHTMARE_ID]: 1,
        [PALEBLOOD_WORM_ID]: 1,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 1,
        [KNIGHT_OF_THE_FEN_ID]: 1,
        [IRONCAST_DEAD_ID]: null,
        [EGGKNIGHT_ID]: 1,
        [PUPPET_KING_EDELHARDT_ID]: null,
        [DEVIL_OF_THE_SMELTED_FEARS_ID]: null,
        [PANZERDRAGON_VELDR_ID]: null,
      },
      {
        [RATWOLVES_ID]: 2,
        [WINGED_NIGHTMARE_ID]: 1,
        [PALEBLOOD_WORM_ID]: 2,
        [PUMPKINHEAD_MONSTROSITIES_ID]: null,
        [KNIGHT_OF_THE_FEN_ID]: 1,
        [IRONCAST_DEAD_ID]: 2,
        [EGGKNIGHT_ID]: null,
        [PUPPET_KING_EDELHARDT_ID]: null,
        [DEVIL_OF_THE_SMELTED_FEARS_ID]: null,
        [PANZERDRAGON_VELDR_ID]: null,
      },
      {
        [RATWOLVES_ID]: 3,
        [WINGED_NIGHTMARE_ID]: 2,
        [PALEBLOOD_WORM_ID]: 2,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 2,
        [KNIGHT_OF_THE_FEN_ID]: 2,
        [IRONCAST_DEAD_ID]: 2,
        [EGGKNIGHT_ID]: 2,
        [PUPPET_KING_EDELHARDT_ID]: 3,
        [DEVIL_OF_THE_SMELTED_FEARS_ID]: 3,
        [PANZERDRAGON_VELDR_ID]: 1,
      },
      {
        [RATWOLVES_ID]: 4,
        [WINGED_NIGHTMARE_ID]: 3,
        [PALEBLOOD_WORM_ID]: 3,
        [PUMPKINHEAD_MONSTROSITIES_ID]: null,
        [KNIGHT_OF_THE_FEN_ID]: null,
        [IRONCAST_DEAD_ID]: 3,
        [EGGKNIGHT_ID]: null,
        [PUPPET_KING_EDELHARDT_ID]: null,
        [DEVIL_OF_THE_SMELTED_FEARS_ID]: null,
        [PANZERDRAGON_VELDR_ID]: null,
      },
      {
        [RATWOLVES_ID]: 4,
        [WINGED_NIGHTMARE_ID]: 3,
        [PALEBLOOD_WORM_ID]: 3,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 3,
        [KNIGHT_OF_THE_FEN_ID]: null,
        [IRONCAST_DEAD_ID]: 3,
        [EGGKNIGHT_ID]: 3,
        [PUPPET_KING_EDELHARDT_ID]: null,
        [DEVIL_OF_THE_SMELTED_FEARS_ID]: 1,
        [PANZERDRAGON_VELDR_ID]: null,
      },
      {
        [RATWOLVES_ID]: 4,
        [WINGED_NIGHTMARE_ID]: 4,
        [PALEBLOOD_WORM_ID]: 3,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 3,
        [KNIGHT_OF_THE_FEN_ID]: 3,
        [IRONCAST_DEAD_ID]: 3,
        [EGGKNIGHT_ID]: 3,
        [PUPPET_KING_EDELHARDT_ID]: 4,
        [DEVIL_OF_THE_SMELTED_FEARS_ID]: 4,
        [PANZERDRAGON_VELDR_ID]: 1,
      },
      {
        [RATWOLVES_ID]: 4,
        [WINGED_NIGHTMARE_ID]: 4,
        [PALEBLOOD_WORM_ID]: 4,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 3,
        [KNIGHT_OF_THE_FEN_ID]: 4,
        [IRONCAST_DEAD_ID]: 4,
        [EGGKNIGHT_ID]: 4,
        [PUPPET_KING_EDELHARDT_ID]: 4,
        [DEVIL_OF_THE_SMELTED_FEARS_ID]: 3,
        [PANZERDRAGON_VELDR_ID]: 2,
      },
      {
        [RATWOLVES_ID]: 4,
        [WINGED_NIGHTMARE_ID]: 4,
        [PALEBLOOD_WORM_ID]: 4,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 4,
        [KNIGHT_OF_THE_FEN_ID]: 4,
        [IRONCAST_DEAD_ID]: 4,
        [EGGKNIGHT_ID]: 4,
        [PUPPET_KING_EDELHARDT_ID]: 4,
        [DEVIL_OF_THE_SMELTED_FEARS_ID]: 3,
        [PANZERDRAGON_VELDR_ID]: 2,
      },
      {
        [RATWOLVES_ID]: 4,
        [WINGED_NIGHTMARE_ID]: 4,
        [PALEBLOOD_WORM_ID]: 4,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 4,
        [KNIGHT_OF_THE_FEN_ID]: 4,
        [IRONCAST_DEAD_ID]: 4,
        [EGGKNIGHT_ID]: 4,
        [PUPPET_KING_EDELHARDT_ID]: 4,
        [DEVIL_OF_THE_SMELTED_FEARS_ID]: 3,
        [PANZERDRAGON_VELDR_ID]: 2,
      },
      {
        [RATWOLVES_ID]: 4,
        [WINGED_NIGHTMARE_ID]: 4,
        [PALEBLOOD_WORM_ID]: 4,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 4,
        [KNIGHT_OF_THE_FEN_ID]: 4,
        [IRONCAST_DEAD_ID]: 4,
        [EGGKNIGHT_ID]: 4,
        [PUPPET_KING_EDELHARDT_ID]: 4,
        [DEVIL_OF_THE_SMELTED_FEARS_ID]: 3,
        [PANZERDRAGON_VELDR_ID]: 2,
      },
    ],
  },
  adventures: [],
};
