import {
  DEVIL_OF_THE_ANCIENT_DUSK_ID,
  FIRST_MEN_WARRIORS_ID,
  HAUNTS_OF_UTREBANT_ID,
  KING_LAID_LOW_ID,
  KNIGHT_OF_THE_FEN_ID,
  PALEBLOOD_WORM_ID,
  PUMPKINHEAD_MONSTROSITIES_ID,
  RATWOLVES_ID,
  TOADRAGON_ID,
  WHITE_APE_TROLL_ID,
  WINGED_NIGHTMARE_ID,
} from '@/catalogs/monsters';
import type { KingdomCatalog } from '@/models/kingdom';
export const SUNKEN_ID = 'sunken-kingdom';

const ORDER = [
  RATWOLVES_ID,
  WINGED_NIGHTMARE_ID,
  PALEBLOOD_WORM_ID,
  PUMPKINHEAD_MONSTROSITIES_ID,
  KNIGHT_OF_THE_FEN_ID,
  FIRST_MEN_WARRIORS_ID,
  HAUNTS_OF_UTREBANT_ID,
  WHITE_APE_TROLL_ID,
  KING_LAID_LOW_ID,
  DEVIL_OF_THE_ANCIENT_DUSK_ID,
  TOADRAGON_ID,
] as const;

export const SUNKEN_KINGDOM: KingdomCatalog = {
  id: 'sunken-kingdom',
  name: 'Sunken Kingdom',
  bestiary: {
    monsters: ORDER.map(id => ({ id })),
    stages: [
      {
        [RATWOLVES_ID]: 1,
        [WINGED_NIGHTMARE_ID]: null,
        [PALEBLOOD_WORM_ID]: 1,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 1,
        [KNIGHT_OF_THE_FEN_ID]: null,
        [FIRST_MEN_WARRIORS_ID]: 1,
        [HAUNTS_OF_UTREBANT_ID]: null,
        [WHITE_APE_TROLL_ID]: 1,
        [KING_LAID_LOW_ID]: null,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: null,
        [TOADRAGON_ID]: null,
      },
      {
        [RATWOLVES_ID]: 1,
        [WINGED_NIGHTMARE_ID]: null,
        [PALEBLOOD_WORM_ID]: 1,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 1,
        [KNIGHT_OF_THE_FEN_ID]: 1,
        [FIRST_MEN_WARRIORS_ID]: 1,
        [HAUNTS_OF_UTREBANT_ID]: 1,
        [WHITE_APE_TROLL_ID]: 1,
        [KING_LAID_LOW_ID]: null,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: null,
        [TOADRAGON_ID]: null,
      },
      {
        [RATWOLVES_ID]: 2,
        [WINGED_NIGHTMARE_ID]: 1,
        [PALEBLOOD_WORM_ID]: 1,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 1,
        [KNIGHT_OF_THE_FEN_ID]: 1,
        [FIRST_MEN_WARRIORS_ID]: null,
        [HAUNTS_OF_UTREBANT_ID]: 1,
        [WHITE_APE_TROLL_ID]: 1,
        [KING_LAID_LOW_ID]: null,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: null,
        [TOADRAGON_ID]: null,
      },
      {
        [RATWOLVES_ID]: 2,
        [WINGED_NIGHTMARE_ID]: 1,
        [PALEBLOOD_WORM_ID]: 2,
        [PUMPKINHEAD_MONSTROSITIES_ID]: null,
        [KNIGHT_OF_THE_FEN_ID]: 1,
        [FIRST_MEN_WARRIORS_ID]: 2,
        [HAUNTS_OF_UTREBANT_ID]: 1,
        [WHITE_APE_TROLL_ID]: null,
        [KING_LAID_LOW_ID]: null,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: null,
        [TOADRAGON_ID]: null,
      },
      {
        [RATWOLVES_ID]: 2,
        [WINGED_NIGHTMARE_ID]: 1,
        [PALEBLOOD_WORM_ID]: 2,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 2,
        [KNIGHT_OF_THE_FEN_ID]: null,
        [FIRST_MEN_WARRIORS_ID]: 2,
        [HAUNTS_OF_UTREBANT_ID]: null,
        [WHITE_APE_TROLL_ID]: 2,
        [KING_LAID_LOW_ID]: null,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: null,
        [TOADRAGON_ID]: null,
      },
      {
        [RATWOLVES_ID]: null,
        [WINGED_NIGHTMARE_ID]: 2,
        [PALEBLOOD_WORM_ID]: 2,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 2,
        [KNIGHT_OF_THE_FEN_ID]: null,
        [FIRST_MEN_WARRIORS_ID]: 2,
        [HAUNTS_OF_UTREBANT_ID]: 2,
        [WHITE_APE_TROLL_ID]: 2,
        [KING_LAID_LOW_ID]: null,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: null,
        [TOADRAGON_ID]: null,
      },
      {
        [RATWOLVES_ID]: 3,
        [WINGED_NIGHTMARE_ID]: 2,
        [PALEBLOOD_WORM_ID]: null,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 2,
        [KNIGHT_OF_THE_FEN_ID]: 2,
        [FIRST_MEN_WARRIORS_ID]: null,
        [HAUNTS_OF_UTREBANT_ID]: 2,
        [WHITE_APE_TROLL_ID]: 2,
        [KING_LAID_LOW_ID]: null,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: null,
        [TOADRAGON_ID]: null,
      },
      {
        [RATWOLVES_ID]: 3,
        [WINGED_NIGHTMARE_ID]: 2,
        [PALEBLOOD_WORM_ID]: 3,
        [PUMPKINHEAD_MONSTROSITIES_ID]: null,
        [KNIGHT_OF_THE_FEN_ID]: 2,
        [FIRST_MEN_WARRIORS_ID]: 3,
        [HAUNTS_OF_UTREBANT_ID]: 2,
        [WHITE_APE_TROLL_ID]: null,
        [KING_LAID_LOW_ID]: null,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: null,
        [TOADRAGON_ID]: null,
      },
      {
        [RATWOLVES_ID]: 3,
        [WINGED_NIGHTMARE_ID]: null,
        [PALEBLOOD_WORM_ID]: 3,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 3,
        [KNIGHT_OF_THE_FEN_ID]: 2,
        [FIRST_MEN_WARRIORS_ID]: 2,
        [HAUNTS_OF_UTREBANT_ID]: 3,
        [WHITE_APE_TROLL_ID]: 1,
        [KING_LAID_LOW_ID]: null,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: null,
        [TOADRAGON_ID]: null,
      },
      {
        [RATWOLVES_ID]: 4,
        [WINGED_NIGHTMARE_ID]: 3,
        [PALEBLOOD_WORM_ID]: 3,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 3,
        [KNIGHT_OF_THE_FEN_ID]: null,
        [FIRST_MEN_WARRIORS_ID]: 3,
        [HAUNTS_OF_UTREBANT_ID]: 3,
        [WHITE_APE_TROLL_ID]: 1,
        [KING_LAID_LOW_ID]: null,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: null,
        [TOADRAGON_ID]: null,
      },
      {
        [RATWOLVES_ID]: 4,
        [WINGED_NIGHTMARE_ID]: 3,
        [PALEBLOOD_WORM_ID]: null,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 3,
        [KNIGHT_OF_THE_FEN_ID]: 3,
        [FIRST_MEN_WARRIORS_ID]: null,
        [HAUNTS_OF_UTREBANT_ID]: 3,
        [WHITE_APE_TROLL_ID]: 2,
        [KING_LAID_LOW_ID]: null,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: null,
        [TOADRAGON_ID]: null,
      },
      {
        [RATWOLVES_ID]: 4,
        [WINGED_NIGHTMARE_ID]: null,
        [PALEBLOOD_WORM_ID]: null,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 3,
        [KNIGHT_OF_THE_FEN_ID]: 3,
        [FIRST_MEN_WARRIORS_ID]: 2,
        [HAUNTS_OF_UTREBANT_ID]: 3,
        [WHITE_APE_TROLL_ID]: 2,
        [KING_LAID_LOW_ID]: 1,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: null,
        [TOADRAGON_ID]: null,
      },
      {
        [RATWOLVES_ID]: null,
        [WINGED_NIGHTMARE_ID]: null,
        [PALEBLOOD_WORM_ID]: 4,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 3,
        [KNIGHT_OF_THE_FEN_ID]: 3,
        [FIRST_MEN_WARRIORS_ID]: null,
        [HAUNTS_OF_UTREBANT_ID]: 2,
        [WHITE_APE_TROLL_ID]: 1,
        [KING_LAID_LOW_ID]: null,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: null,
        [TOADRAGON_ID]: null,
      },
      {
        [RATWOLVES_ID]: null,
        [WINGED_NIGHTMARE_ID]: null,
        [PALEBLOOD_WORM_ID]: 4,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 4,
        [KNIGHT_OF_THE_FEN_ID]: null,
        [FIRST_MEN_WARRIORS_ID]: 4,
        [HAUNTS_OF_UTREBANT_ID]: null,
        [WHITE_APE_TROLL_ID]: null,
        [KING_LAID_LOW_ID]: 1,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: null,
        [TOADRAGON_ID]: null,
      },
      {
        [RATWOLVES_ID]: null,
        [WINGED_NIGHTMARE_ID]: null,
        [PALEBLOOD_WORM_ID]: 4,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 4,
        [KNIGHT_OF_THE_FEN_ID]: null,
        [FIRST_MEN_WARRIORS_ID]: 4,
        [HAUNTS_OF_UTREBANT_ID]: null,
        [WHITE_APE_TROLL_ID]: null,
        [KING_LAID_LOW_ID]: 2,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: 1,
        [TOADRAGON_ID]: null,
      },
      {
        [RATWOLVES_ID]: null,
        [WINGED_NIGHTMARE_ID]: 4,
        [PALEBLOOD_WORM_ID]: 4,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 4,
        [KNIGHT_OF_THE_FEN_ID]: null,
        [FIRST_MEN_WARRIORS_ID]: null,
        [HAUNTS_OF_UTREBANT_ID]: 4,
        [WHITE_APE_TROLL_ID]: 3,
        [KING_LAID_LOW_ID]: 1,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: null,
        [TOADRAGON_ID]: null,
      },
      {
        [RATWOLVES_ID]: 4,
        [WINGED_NIGHTMARE_ID]: 4,
        [PALEBLOOD_WORM_ID]: 4,
        [PUMPKINHEAD_MONSTROSITIES_ID]: null,
        [KNIGHT_OF_THE_FEN_ID]: 4,
        [FIRST_MEN_WARRIORS_ID]: 4,
        [HAUNTS_OF_UTREBANT_ID]: 4,
        [WHITE_APE_TROLL_ID]: 3,
        [KING_LAID_LOW_ID]: 2,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: 1,
        [TOADRAGON_ID]: null,
      },
      {
        [RATWOLVES_ID]: 4,
        [WINGED_NIGHTMARE_ID]: 4,
        [PALEBLOOD_WORM_ID]: 4,
        [PUMPKINHEAD_MONSTROSITIES_ID]: null,
        [KNIGHT_OF_THE_FEN_ID]: 4,
        [FIRST_MEN_WARRIORS_ID]: 4,
        [HAUNTS_OF_UTREBANT_ID]: 4,
        [WHITE_APE_TROLL_ID]: 3,
        [KING_LAID_LOW_ID]: 2,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: 1,
        [TOADRAGON_ID]: null,
      },
      {
        [RATWOLVES_ID]: null,
        [WINGED_NIGHTMARE_ID]: 4,
        [PALEBLOOD_WORM_ID]: null,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 4,
        [KNIGHT_OF_THE_FEN_ID]: 4,
        [FIRST_MEN_WARRIORS_ID]: 4,
        [HAUNTS_OF_UTREBANT_ID]: null,
        [WHITE_APE_TROLL_ID]: null,
        [KING_LAID_LOW_ID]: 3,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: 2,
        [TOADRAGON_ID]: 1,
      },
      {
        [RATWOLVES_ID]: null,
        [WINGED_NIGHTMARE_ID]: 4,
        [PALEBLOOD_WORM_ID]: null,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 4,
        [KNIGHT_OF_THE_FEN_ID]: 4,
        [FIRST_MEN_WARRIORS_ID]: 4,
        [HAUNTS_OF_UTREBANT_ID]: null,
        [WHITE_APE_TROLL_ID]: null,
        [KING_LAID_LOW_ID]: 4,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: 3,
        [TOADRAGON_ID]: 1,
      },
      {
        [RATWOLVES_ID]: null,
        [WINGED_NIGHTMARE_ID]: 4,
        [PALEBLOOD_WORM_ID]: null,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 4,
        [KNIGHT_OF_THE_FEN_ID]: 4,
        [FIRST_MEN_WARRIORS_ID]: 4,
        [HAUNTS_OF_UTREBANT_ID]: null,
        [WHITE_APE_TROLL_ID]: null,
        [KING_LAID_LOW_ID]: 4,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: 3,
        [TOADRAGON_ID]: 2,
      },
      {
        [RATWOLVES_ID]: null,
        [WINGED_NIGHTMARE_ID]: 4,
        [PALEBLOOD_WORM_ID]: null,
        [PUMPKINHEAD_MONSTROSITIES_ID]: null,
        [KNIGHT_OF_THE_FEN_ID]: 4,
        [FIRST_MEN_WARRIORS_ID]: null,
        [HAUNTS_OF_UTREBANT_ID]: null,
        [WHITE_APE_TROLL_ID]: null,
        [KING_LAID_LOW_ID]: 4,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: 3,
        [TOADRAGON_ID]: 2,
      },
    ],
  },
  adventures: [
    { name: 'Former Glories', roll: { min: 1, max: 3 }, singleAttempt: false },
    { name: 'Sundered Hope', roll: { min: 4, max: 6 }, singleAttempt: true },
    { name: 'Mudfishing', roll: { min: 7, max: 9 }, singleAttempt: false },
    { name: 'Shrine of Remembrance', roll: { min: 10, max: 12 }, singleAttempt: false },
    { name: 'Knots in the Wood', roll: { min: 13, max: 15 }, singleAttempt: false },
    { name: 'Shoulder to the Wheel', roll: { min: 16, max: 18 }, singleAttempt: false },
    { name: 'Rotten to the Core', roll: { min: 19, max: 21 }, singleAttempt: true },
    { name: 'Weight of Guilt', roll: { min: 22, max: 24 }, singleAttempt: true },
    { name: 'Skywatch', roll: { min: 25, max: 27 }, singleAttempt: false },
    { name: 'Life Raft', roll: { min: 28, max: 30 }, singleAttempt: true },
    { name: "In Another's Wake", roll: { min: 31, max: 33 }, singleAttempt: false },
    { name: 'Beguiled', roll: { min: 34, max: 36 }, singleAttempt: false },
    { name: "Nature's Sweet Embrace", roll: { min: 37, max: 40 }, singleAttempt: false },
    { name: 'Rapture of the Deep', roll: { min: 41, max: 44 }, singleAttempt: false },
    { name: 'Disturbed Slumber', roll: { min: 45, max: 48 }, singleAttempt: false },
    { name: 'The Burden of Knowledge', roll: { min: 49, max: 52 }, singleAttempt: true },
    { name: 'Hospitality', roll: { min: 53, max: 56 }, singleAttempt: false },
    { name: 'Wheels of Progress', roll: { min: 57, max: 60 }, singleAttempt: true },
    { name: 'The Scuttling Stones', roll: { min: 61, max: 64 }, singleAttempt: false },
    { name: 'Frail Foundations', roll: { min: 65, max: 68 }, singleAttempt: true },
    { name: 'Cleansing', roll: { min: 69, max: 71 }, singleAttempt: false },
    { name: 'Mudskippers', roll: { min: 72, max: 74 }, singleAttempt: true },
    { name: "Fool's Flame", roll: { min: 75, max: 77 }, singleAttempt: false },
    { name: 'Divine Compassion', roll: { min: 78, max: 80 }, singleAttempt: true },
    { name: 'Buried Truths', roll: { min: 81, max: 83 }, singleAttempt: true },
    { name: 'Shrunken Kingdom', roll: { min: 84, max: 86 }, singleAttempt: true },
    { name: 'Before the Mast', roll: { min: 87, max: 89 }, singleAttempt: true },
    { name: 'Hunter, or Hunted?', roll: { min: 90, max: 92 }, singleAttempt: false },
    { name: 'High Stakes', roll: { min: 93, max: 95 }, singleAttempt: true },
    {
      name: "Idle Playthings in the Devil's Hands",
      roll: { min: 96, max: 100 },
      singleAttempt: true,
    },
  ],
};
