import type { KingdomCatalog } from '@/models/kingdom';
import {
  // existing ones from your earlier list
  IRONCAST_DEAD_ID,
  EGGKNIGHT_ID,
  PUPPET_KING_EDELHARDT_ID,
  DEVIL_OF_THE_SMELTED_FEARS_ID,
  PANZERDRAGON_VELDR_ID,
  RATWOLVES_ID,
  WINGED_NIGHTMARE_ID,
  PALEBLOOD_WORM_ID,
  PUMPKINHEAD_MONSTROSITIES_ID,
  KNIGHT_OF_THE_FEN_ID,
  PANZERGEIST_ID,
  STONEMASON_KNIGHT_ID,
  KNIGHTEATER_ID,
  YOUNG_DEVOURER_DRAGON_ID,
  FIRST_MEN_WARRIORS_ID,
  FIRST_MEN_LICTOR_HUNTERS_ID,
  HAUNTS_OF_UTREBANT_ID,
  WHITE_APE_TROLL_ID,
  BOG_WITCH_ID,
  KING_LAID_LOW_ID,
  DEVIL_OF_THE_ANCIENT_DUSK_ID,
  TOADRAGON_ID,
} from '@/catalogs/monsters';

export const TEN_THOUSAND_SUCCULENT_FEARS: KingdomCatalog = {
  id: 'ten-thousand-succulent-fears',
  name: 'Ten Thousand Succulent Fears',
  bestiary: {
    monsters: [
      { id: PANZERGEIST_ID },
      { id: IRONCAST_DEAD_ID },
      { id: EGGKNIGHT_ID },
      { id: STONEMASON_KNIGHT_ID },
      { id: PUPPET_KING_EDELHARDT_ID },
      { id: DEVIL_OF_THE_SMELTED_FEARS_ID },
      { id: PANZERDRAGON_VELDR_ID },
      { id: RATWOLVES_ID },
      { id: WINGED_NIGHTMARE_ID },
      { id: PALEBLOOD_WORM_ID },
      { id: PUMPKINHEAD_MONSTROSITIES_ID },
      { id: KNIGHT_OF_THE_FEN_ID },
      { id: KNIGHTEATER_ID },
      { id: YOUNG_DEVOURER_DRAGON_ID },
      { id: FIRST_MEN_WARRIORS_ID },
      { id: FIRST_MEN_LICTOR_HUNTERS_ID },
      { id: HAUNTS_OF_UTREBANT_ID },
      { id: WHITE_APE_TROLL_ID },
      { id: BOG_WITCH_ID },
      { id: KING_LAID_LOW_ID },
      { id: DEVIL_OF_THE_ANCIENT_DUSK_ID },
      { id: TOADRAGON_ID },
    ],
    stages: [
      {
        [PANZERGEIST_ID]: 1,
        [IRONCAST_DEAD_ID]: 1,
        [EGGKNIGHT_ID]: 1,
        [STONEMASON_KNIGHT_ID]: null,
        [PUPPET_KING_EDELHARDT_ID]: null,
        [DEVIL_OF_THE_SMELTED_FEARS_ID]: null,
        [PANZERDRAGON_VELDR_ID]: null,
        [RATWOLVES_ID]: 1,
        [WINGED_NIGHTMARE_ID]: null,
        [PALEBLOOD_WORM_ID]: 1,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 1,
        [KNIGHT_OF_THE_FEN_ID]: null,
        [KNIGHTEATER_ID]: null,
        [YOUNG_DEVOURER_DRAGON_ID]: null,
        [FIRST_MEN_WARRIORS_ID]: 1,
        [FIRST_MEN_LICTOR_HUNTERS_ID]: 1,
        [HAUNTS_OF_UTREBANT_ID]: null,
        [WHITE_APE_TROLL_ID]: 1,
        [BOG_WITCH_ID]: null,
        [KING_LAID_LOW_ID]: null,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: null,
        [TOADRAGON_ID]: null,
      },
      {
        [PANZERGEIST_ID]: 1,
        [IRONCAST_DEAD_ID]: 1,
        [EGGKNIGHT_ID]: 1,
        [STONEMASON_KNIGHT_ID]: 1,
        [PUPPET_KING_EDELHARDT_ID]: null,
        [DEVIL_OF_THE_SMELTED_FEARS_ID]: null,
        [PANZERDRAGON_VELDR_ID]: null,
        [RATWOLVES_ID]: 1,
        [WINGED_NIGHTMARE_ID]: null,
        [PALEBLOOD_WORM_ID]: 1,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 1,
        [KNIGHT_OF_THE_FEN_ID]: 1,
        [KNIGHTEATER_ID]: null,
        [YOUNG_DEVOURER_DRAGON_ID]: null,
        [FIRST_MEN_WARRIORS_ID]: 1,
        [FIRST_MEN_LICTOR_HUNTERS_ID]: 1,
        [HAUNTS_OF_UTREBANT_ID]: 1,
        [WHITE_APE_TROLL_ID]: 1,
        [BOG_WITCH_ID]: null,
        [KING_LAID_LOW_ID]: null,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: null,
        [TOADRAGON_ID]: null,
      },
      {
        [PANZERGEIST_ID]: 1,
        [IRONCAST_DEAD_ID]: null,
        [EGGKNIGHT_ID]: 1,
        [STONEMASON_KNIGHT_ID]: 1,
        [PUPPET_KING_EDELHARDT_ID]: null,
        [DEVIL_OF_THE_SMELTED_FEARS_ID]: null,
        [PANZERDRAGON_VELDR_ID]: null,
        [RATWOLVES_ID]: 2,
        [WINGED_NIGHTMARE_ID]: 1,
        [PALEBLOOD_WORM_ID]: 1,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 1,
        [KNIGHT_OF_THE_FEN_ID]: 1,
        [KNIGHTEATER_ID]: 1,
        [YOUNG_DEVOURER_DRAGON_ID]: null,
        [FIRST_MEN_WARRIORS_ID]: null,
        [FIRST_MEN_LICTOR_HUNTERS_ID]: 1,
        [HAUNTS_OF_UTREBANT_ID]: 1,
        [WHITE_APE_TROLL_ID]: 1,
        [BOG_WITCH_ID]: 1,
        [KING_LAID_LOW_ID]: null,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: null,
        [TOADRAGON_ID]: null,
      },
      {
        [PANZERGEIST_ID]: null,
        [IRONCAST_DEAD_ID]: 2,
        [EGGKNIGHT_ID]: null,
        [STONEMASON_KNIGHT_ID]: 1,
        [PUPPET_KING_EDELHARDT_ID]: null,
        [DEVIL_OF_THE_SMELTED_FEARS_ID]: null,
        [PANZERDRAGON_VELDR_ID]: null,
        [RATWOLVES_ID]: 2,
        [WINGED_NIGHTMARE_ID]: 1,
        [PALEBLOOD_WORM_ID]: 2,
        [PUMPKINHEAD_MONSTROSITIES_ID]: null,
        [KNIGHT_OF_THE_FEN_ID]: 1,
        [KNIGHTEATER_ID]: 1,
        [YOUNG_DEVOURER_DRAGON_ID]: null,
        [FIRST_MEN_WARRIORS_ID]: 2,
        [FIRST_MEN_LICTOR_HUNTERS_ID]: 2,
        [HAUNTS_OF_UTREBANT_ID]: 1,
        [WHITE_APE_TROLL_ID]: null,
        [BOG_WITCH_ID]: 1,
        [KING_LAID_LOW_ID]: null,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: null,
        [TOADRAGON_ID]: null,
      },
      {
        [PANZERGEIST_ID]: 2,
        [IRONCAST_DEAD_ID]: 2,
        [EGGKNIGHT_ID]: 2,
        [STONEMASON_KNIGHT_ID]: null,
        [PUPPET_KING_EDELHARDT_ID]: null,
        [DEVIL_OF_THE_SMELTED_FEARS_ID]: null,
        [PANZERDRAGON_VELDR_ID]: null,
        [RATWOLVES_ID]: 2,
        [WINGED_NIGHTMARE_ID]: 1,
        [PALEBLOOD_WORM_ID]: 2,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 2,
        [KNIGHT_OF_THE_FEN_ID]: null,
        [KNIGHTEATER_ID]: 1,
        [YOUNG_DEVOURER_DRAGON_ID]: null,
        [FIRST_MEN_WARRIORS_ID]: 2,
        [FIRST_MEN_LICTOR_HUNTERS_ID]: 2,
        [HAUNTS_OF_UTREBANT_ID]: null,
        [WHITE_APE_TROLL_ID]: 2,
        [BOG_WITCH_ID]: 1,
        [KING_LAID_LOW_ID]: null,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: null,
        [TOADRAGON_ID]: null,
      },
      {
        [PANZERGEIST_ID]: 2,
        [IRONCAST_DEAD_ID]: 2,
        [EGGKNIGHT_ID]: 2,
        [STONEMASON_KNIGHT_ID]: 2,
        [PUPPET_KING_EDELHARDT_ID]: null,
        [DEVIL_OF_THE_SMELTED_FEARS_ID]: null,
        [PANZERDRAGON_VELDR_ID]: null,
        [RATWOLVES_ID]: null,
        [WINGED_NIGHTMARE_ID]: 2,
        [PALEBLOOD_WORM_ID]: 2,
        [PUMPKINHEAD_MONSTROSITIES_ID]: null,
        [KNIGHT_OF_THE_FEN_ID]: null,
        [KNIGHTEATER_ID]: null,
        [YOUNG_DEVOURER_DRAGON_ID]: 2,
        [FIRST_MEN_WARRIORS_ID]: 2,
        [FIRST_MEN_LICTOR_HUNTERS_ID]: 2,
        [HAUNTS_OF_UTREBANT_ID]: 2,
        [WHITE_APE_TROLL_ID]: null,
        [BOG_WITCH_ID]: null,
        [KING_LAID_LOW_ID]: null,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: null,
        [TOADRAGON_ID]: null,
      },
      {
        [PANZERGEIST_ID]: 2,
        [IRONCAST_DEAD_ID]: null,
        [EGGKNIGHT_ID]: 2,
        [STONEMASON_KNIGHT_ID]: 2,
        [PUPPET_KING_EDELHARDT_ID]: null,
        [DEVIL_OF_THE_SMELTED_FEARS_ID]: null,
        [PANZERDRAGON_VELDR_ID]: null,
        [RATWOLVES_ID]: 3,
        [WINGED_NIGHTMARE_ID]: 2,
        [PALEBLOOD_WORM_ID]: null,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 2,
        [KNIGHT_OF_THE_FEN_ID]: 2,
        [KNIGHTEATER_ID]: 2,
        [YOUNG_DEVOURER_DRAGON_ID]: null,
        [FIRST_MEN_WARRIORS_ID]: null,
        [FIRST_MEN_LICTOR_HUNTERS_ID]: 2,
        [HAUNTS_OF_UTREBANT_ID]: 2,
        [WHITE_APE_TROLL_ID]: 2,
        [BOG_WITCH_ID]: null,
        [KING_LAID_LOW_ID]: null,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: null,
        [TOADRAGON_ID]: null,
      },
      {
        [PANZERGEIST_ID]: null,
        [IRONCAST_DEAD_ID]: 3,
        [EGGKNIGHT_ID]: null,
        [STONEMASON_KNIGHT_ID]: 2,
        [PUPPET_KING_EDELHARDT_ID]: 1,
        [DEVIL_OF_THE_SMELTED_FEARS_ID]: null,
        [PANZERDRAGON_VELDR_ID]: null,
        [RATWOLVES_ID]: 3,
        [WINGED_NIGHTMARE_ID]: 2,
        [PALEBLOOD_WORM_ID]: 3,
        [PUMPKINHEAD_MONSTROSITIES_ID]: null,
        [KNIGHT_OF_THE_FEN_ID]: 2,
        [KNIGHTEATER_ID]: 2,
        [YOUNG_DEVOURER_DRAGON_ID]: null,
        [FIRST_MEN_WARRIORS_ID]: 3,
        [FIRST_MEN_LICTOR_HUNTERS_ID]: 3,
        [HAUNTS_OF_UTREBANT_ID]: 2,
        [WHITE_APE_TROLL_ID]: null,
        [BOG_WITCH_ID]: 2,
        [KING_LAID_LOW_ID]: 1,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: null,
        [TOADRAGON_ID]: null,
      },
      {
        [PANZERGEIST_ID]: 3,
        [IRONCAST_DEAD_ID]: 3,
        [EGGKNIGHT_ID]: 3,
        [STONEMASON_KNIGHT_ID]: null,
        [PUPPET_KING_EDELHARDT_ID]: 1,
        [DEVIL_OF_THE_SMELTED_FEARS_ID]: null,
        [PANZERDRAGON_VELDR_ID]: null,
        [RATWOLVES_ID]: 3,
        [WINGED_NIGHTMARE_ID]: null,
        [PALEBLOOD_WORM_ID]: 3,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 3,
        [KNIGHT_OF_THE_FEN_ID]: 2,
        [KNIGHTEATER_ID]: 2,
        [YOUNG_DEVOURER_DRAGON_ID]: null,
        [FIRST_MEN_WARRIORS_ID]: 3,
        [FIRST_MEN_LICTOR_HUNTERS_ID]: 3,
        [HAUNTS_OF_UTREBANT_ID]: null,
        [WHITE_APE_TROLL_ID]: 3,
        [BOG_WITCH_ID]: 2,
        [KING_LAID_LOW_ID]: 1,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: null,
        [TOADRAGON_ID]: null,
      },
      {
        [PANZERGEIST_ID]: 3,
        [IRONCAST_DEAD_ID]: 3,
        [EGGKNIGHT_ID]: 3,
        [STONEMASON_KNIGHT_ID]: null,
        [PUPPET_KING_EDELHARDT_ID]: 1,
        [DEVIL_OF_THE_SMELTED_FEARS_ID]: null,
        [PANZERDRAGON_VELDR_ID]: null,
        [RATWOLVES_ID]: 4,
        [WINGED_NIGHTMARE_ID]: 3,
        [PALEBLOOD_WORM_ID]: 3,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 3,
        [KNIGHT_OF_THE_FEN_ID]: null,
        [KNIGHTEATER_ID]: null,
        [YOUNG_DEVOURER_DRAGON_ID]: 3,
        [FIRST_MEN_WARRIORS_ID]: 3,
        [FIRST_MEN_LICTOR_HUNTERS_ID]: 3,
        [HAUNTS_OF_UTREBANT_ID]: 3,
        [WHITE_APE_TROLL_ID]: null,
        [BOG_WITCH_ID]: 1,
        [KING_LAID_LOW_ID]: null,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: null,
        [TOADRAGON_ID]: null,
      },
      {
        [PANZERGEIST_ID]: 3,
        [IRONCAST_DEAD_ID]: null,
        [EGGKNIGHT_ID]: 3,
        [STONEMASON_KNIGHT_ID]: 3,
        [PUPPET_KING_EDELHARDT_ID]: 2,
        [DEVIL_OF_THE_SMELTED_FEARS_ID]: null,
        [PANZERDRAGON_VELDR_ID]: null,
        [RATWOLVES_ID]: 4,
        [WINGED_NIGHTMARE_ID]: 3,
        [PALEBLOOD_WORM_ID]: null,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 3,
        [KNIGHT_OF_THE_FEN_ID]: 3,
        [KNIGHTEATER_ID]: null,
        [YOUNG_DEVOURER_DRAGON_ID]: null,
        [FIRST_MEN_WARRIORS_ID]: null,
        [FIRST_MEN_LICTOR_HUNTERS_ID]: 3,
        [HAUNTS_OF_UTREBANT_ID]: 3,
        [WHITE_APE_TROLL_ID]: null,
        [BOG_WITCH_ID]: 2,
        [KING_LAID_LOW_ID]: null,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: null,
        [TOADRAGON_ID]: null,
      },
      {
        [PANZERGEIST_ID]: null,
        [IRONCAST_DEAD_ID]: 4,
        [EGGKNIGHT_ID]: null,
        [STONEMASON_KNIGHT_ID]: 3,
        [PUPPET_KING_EDELHARDT_ID]: 2,
        [DEVIL_OF_THE_SMELTED_FEARS_ID]: 1,
        [PANZERDRAGON_VELDR_ID]: null,
        [RATWOLVES_ID]: 4,
        [WINGED_NIGHTMARE_ID]: 3,
        [PALEBLOOD_WORM_ID]: null,
        [PUMPKINHEAD_MONSTROSITIES_ID]: null,
        [KNIGHT_OF_THE_FEN_ID]: 3,
        [KNIGHTEATER_ID]: 3,
        [YOUNG_DEVOURER_DRAGON_ID]: null,
        [FIRST_MEN_WARRIORS_ID]: 4,
        [FIRST_MEN_LICTOR_HUNTERS_ID]: null,
        [HAUNTS_OF_UTREBANT_ID]: 3,
        [WHITE_APE_TROLL_ID]: null,
        [BOG_WITCH_ID]: 3,
        [KING_LAID_LOW_ID]: 2,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: 1,
        [TOADRAGON_ID]: null,
      },
      {
        [PANZERGEIST_ID]: 4,
        [IRONCAST_DEAD_ID]: 4,
        [EGGKNIGHT_ID]: null,
        [STONEMASON_KNIGHT_ID]: 3,
        [PUPPET_KING_EDELHARDT_ID]: 2,
        [DEVIL_OF_THE_SMELTED_FEARS_ID]: 1,
        [PANZERDRAGON_VELDR_ID]: null,
        [RATWOLVES_ID]: null,
        [WINGED_NIGHTMARE_ID]: null,
        [PALEBLOOD_WORM_ID]: 4,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 4,
        [KNIGHT_OF_THE_FEN_ID]: 3,
        [KNIGHTEATER_ID]: 3,
        [YOUNG_DEVOURER_DRAGON_ID]: null,
        [FIRST_MEN_WARRIORS_ID]: 4,
        [FIRST_MEN_LICTOR_HUNTERS_ID]: 4,
        [HAUNTS_OF_UTREBANT_ID]: null,
        [WHITE_APE_TROLL_ID]: null,
        [BOG_WITCH_ID]: 3,
        [KING_LAID_LOW_ID]: 2,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: 1,
        [TOADRAGON_ID]: null,
      },
      {
        [PANZERGEIST_ID]: 4,
        [IRONCAST_DEAD_ID]: 4,
        [EGGKNIGHT_ID]: 4,
        [STONEMASON_KNIGHT_ID]: null,
        [PUPPET_KING_EDELHARDT_ID]: 3,
        [DEVIL_OF_THE_SMELTED_FEARS_ID]: 1,
        [PANZERDRAGON_VELDR_ID]: null,
        [RATWOLVES_ID]: null,
        [WINGED_NIGHTMARE_ID]: null,
        [PALEBLOOD_WORM_ID]: 4,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 4,
        [KNIGHT_OF_THE_FEN_ID]: null,
        [KNIGHTEATER_ID]: 3,
        [YOUNG_DEVOURER_DRAGON_ID]: 4,
        [FIRST_MEN_WARRIORS_ID]: 4,
        [FIRST_MEN_LICTOR_HUNTERS_ID]: 4,
        [HAUNTS_OF_UTREBANT_ID]: 4,
        [WHITE_APE_TROLL_ID]: 3,
        [BOG_WITCH_ID]: 3,
        [KING_LAID_LOW_ID]: 1,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: null,
        [TOADRAGON_ID]: null,
      },
      {
        [PANZERGEIST_ID]: 4,
        [IRONCAST_DEAD_ID]: null,
        [EGGKNIGHT_ID]: 4,
        [STONEMASON_KNIGHT_ID]: null,
        [PUPPET_KING_EDELHARDT_ID]: 3,
        [DEVIL_OF_THE_SMELTED_FEARS_ID]: 2,
        [PANZERDRAGON_VELDR_ID]: null,
        [RATWOLVES_ID]: null,
        [WINGED_NIGHTMARE_ID]: 4,
        [PALEBLOOD_WORM_ID]: 4,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 4,
        [KNIGHT_OF_THE_FEN_ID]: null,
        [KNIGHTEATER_ID]: null,
        [YOUNG_DEVOURER_DRAGON_ID]: null,
        [FIRST_MEN_WARRIORS_ID]: 4,
        [FIRST_MEN_LICTOR_HUNTERS_ID]: 4,
        [HAUNTS_OF_UTREBANT_ID]: 4,
        [WHITE_APE_TROLL_ID]: null,
        [BOG_WITCH_ID]: 3,
        [KING_LAID_LOW_ID]: 2,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: null,
        [TOADRAGON_ID]: null,
      },
      {
        [PANZERGEIST_ID]: null,
        [IRONCAST_DEAD_ID]: null,
        [EGGKNIGHT_ID]: 4,
        [STONEMASON_KNIGHT_ID]: 4,
        [PUPPET_KING_EDELHARDT_ID]: 3,
        [DEVIL_OF_THE_SMELTED_FEARS_ID]: 2,
        [PANZERDRAGON_VELDR_ID]: 1,
        [RATWOLVES_ID]: null,
        [WINGED_NIGHTMARE_ID]: 4,
        [PALEBLOOD_WORM_ID]: null,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 4,
        [KNIGHT_OF_THE_FEN_ID]: null,
        [KNIGHTEATER_ID]: 1,
        [YOUNG_DEVOURER_DRAGON_ID]: null,
        [FIRST_MEN_WARRIORS_ID]: null,
        [FIRST_MEN_LICTOR_HUNTERS_ID]: null,
        [HAUNTS_OF_UTREBANT_ID]: 4,
        [WHITE_APE_TROLL_ID]: 4,
        [BOG_WITCH_ID]: null,
        [KING_LAID_LOW_ID]: 3,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: 2,
        [TOADRAGON_ID]: 1,
      },
      {
        [PANZERGEIST_ID]: null,
        [IRONCAST_DEAD_ID]: null,
        [EGGKNIGHT_ID]: null,
        [STONEMASON_KNIGHT_ID]: 4,
        [PUPPET_KING_EDELHARDT_ID]: 4,
        [DEVIL_OF_THE_SMELTED_FEARS_ID]: 2,
        [PANZERDRAGON_VELDR_ID]: 1,
        [RATWOLVES_ID]: null,
        [WINGED_NIGHTMARE_ID]: 4,
        [PALEBLOOD_WORM_ID]: null,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 4,
        [KNIGHT_OF_THE_FEN_ID]: 4,
        [KNIGHTEATER_ID]: 1,
        [YOUNG_DEVOURER_DRAGON_ID]: null,
        [FIRST_MEN_WARRIORS_ID]: null,
        [FIRST_MEN_LICTOR_HUNTERS_ID]: null,
        [HAUNTS_OF_UTREBANT_ID]: null,
        [WHITE_APE_TROLL_ID]: null,
        [BOG_WITCH_ID]: 4,
        [KING_LAID_LOW_ID]: 4,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: 2,
        [TOADRAGON_ID]: 1,
      },
      {
        [PANZERGEIST_ID]: null,
        [IRONCAST_DEAD_ID]: null,
        [EGGKNIGHT_ID]: null,
        [STONEMASON_KNIGHT_ID]: 4,
        [PUPPET_KING_EDELHARDT_ID]: 4,
        [DEVIL_OF_THE_SMELTED_FEARS_ID]: 3,
        [PANZERDRAGON_VELDR_ID]: 1,
        [RATWOLVES_ID]: null,
        [WINGED_NIGHTMARE_ID]: 4,
        [PALEBLOOD_WORM_ID]: null,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 4,
        [KNIGHT_OF_THE_FEN_ID]: 4,
        [KNIGHTEATER_ID]: 1,
        [YOUNG_DEVOURER_DRAGON_ID]: null,
        [FIRST_MEN_WARRIORS_ID]: null,
        [FIRST_MEN_LICTOR_HUNTERS_ID]: null,
        [HAUNTS_OF_UTREBANT_ID]: null,
        [WHITE_APE_TROLL_ID]: null,
        [BOG_WITCH_ID]: 4,
        [KING_LAID_LOW_ID]: 4,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: 3,
        [TOADRAGON_ID]: 1,
      },
      {
        [PANZERGEIST_ID]: null,
        [IRONCAST_DEAD_ID]: null,
        [EGGKNIGHT_ID]: null,
        [STONEMASON_KNIGHT_ID]: 4,
        [PUPPET_KING_EDELHARDT_ID]: 4,
        [DEVIL_OF_THE_SMELTED_FEARS_ID]: 3,
        [PANZERDRAGON_VELDR_ID]: 2,
        [RATWOLVES_ID]: null,
        [WINGED_NIGHTMARE_ID]: 4,
        [PALEBLOOD_WORM_ID]: null,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 4,
        [KNIGHT_OF_THE_FEN_ID]: 4,
        [KNIGHTEATER_ID]: 2,
        [YOUNG_DEVOURER_DRAGON_ID]: null,
        [FIRST_MEN_WARRIORS_ID]: null,
        [FIRST_MEN_LICTOR_HUNTERS_ID]: null,
        [HAUNTS_OF_UTREBANT_ID]: null,
        [WHITE_APE_TROLL_ID]: null,
        [BOG_WITCH_ID]: 4,
        [KING_LAID_LOW_ID]: 4,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: 3,
        [TOADRAGON_ID]: 2,
      },
      {
        [PANZERGEIST_ID]: null,
        [IRONCAST_DEAD_ID]: null,
        [EGGKNIGHT_ID]: null,
        [STONEMASON_KNIGHT_ID]: 4,
        [PUPPET_KING_EDELHARDT_ID]: 4,
        [DEVIL_OF_THE_SMELTED_FEARS_ID]: 3,
        [PANZERDRAGON_VELDR_ID]: 2,
        [RATWOLVES_ID]: null,
        [WINGED_NIGHTMARE_ID]: 4,
        [PALEBLOOD_WORM_ID]: null,
        [PUMPKINHEAD_MONSTROSITIES_ID]: 4,
        [KNIGHT_OF_THE_FEN_ID]: 4,
        [KNIGHTEATER_ID]: 2,
        [YOUNG_DEVOURER_DRAGON_ID]: null,
        [FIRST_MEN_WARRIORS_ID]: null,
        [FIRST_MEN_LICTOR_HUNTERS_ID]: null,
        [HAUNTS_OF_UTREBANT_ID]: null,
        [WHITE_APE_TROLL_ID]: null,
        [BOG_WITCH_ID]: 4,
        [KING_LAID_LOW_ID]: 4,
        [DEVIL_OF_THE_ANCIENT_DUSK_ID]: 3,
        [TOADRAGON_ID]: 2,
      },
    ],
  },
  adventures: [
    { name: 'Gardens of Envy', roll: { min: 1, max: 5 }, singleAttempt: false },
    { name: "Traitor's Crossing", roll: { min: 6, max: 11 }, singleAttempt: true },
    { name: 'Fated Pilgrimage', roll: { min: 12, max: 18 }, singleAttempt: true },
    { name: 'Solitary Confinement', roll: { min: 19, max: 25 }, singleAttempt: true },
    { name: 'Wyrmery', roll: { min: 26, max: 32 }, singleAttempt: false },
    { name: 'Quake', roll: { min: 33, max: 39 }, singleAttempt: false },
    { name: "Defiance's Spoils", roll: { min: 40, max: 46 }, singleAttempt: true },
    { name: 'Heroic End', roll: { min: 47, max: 53 }, singleAttempt: false },
    { name: 'Corrosive Spiral', roll: { min: 54, max: 60 }, singleAttempt: false },
    { name: 'In Tandem', roll: { min: 61, max: 67 }, singleAttempt: true },
    { name: 'Heartburn', roll: { min: 68, max: 74 }, singleAttempt: true },
    { name: 'Free at Last', roll: { min: 75, max: 81 }, singleAttempt: false },
    { name: 'Stonemen', roll: { min: 82, max: 88 }, singleAttempt: false },
    { name: 'Escape This Cage of Flesh', roll: { min: 89, max: 94 }, singleAttempt: true },
    { name: 'Profane Terror', roll: { min: 95, max: 100 }, singleAttempt: true },
  ],
};
