export enum Tier {
  mob = 'mob',
  vassal = 'vassal',
  devil = 'devil',
  king = 'king',
  dragon = 'dragon',
  legendary = 'legendary',
}

export enum MonsterType {
  ancient = 'ancient',
  ape = 'ape',
  beast = 'beast',
  blood = 'blood',
  calamity = 'calamity',
  construct = 'construct',
  cursed = 'cursed',
  egg = 'egg',
  horror = 'horror',
  hunger = 'hunger',
  hunter = 'hunter',
  knight = 'knight',
  machinated = 'machinated',
  ooze = 'ooze',
  parasite = 'parasite',
  plant = 'plant',
  soldier = 'soldier',
  spellcaster = 'spellcaster',
  stone = 'stone',
  toad = 'toad',
  undead = 'undead',
}
