import { activationCounter, ActivationToken, MonsterStats } from '@/models/monster';
import { MonsterType, Tier } from '../tier';

export const BOG_WITCH_ID = 'bog-witch';

export const bogWitch: ReadonlyArray<MonsterStats> = [
  Object.freeze({
    id: BOG_WITCH_ID,
    name: 'Bog Witch',
    tier: Tier.vassal,
    type: [MonsterType.spellcaster, MonsterType.ancient],
    level: 1,
    toHit: 4,
    accuracy: 5,
    wounds: 8,
    exhibitionStartingWounds: 2,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
  }),
  Object.freeze({
    id: BOG_WITCH_ID,
    name: 'Bog Witch',
    tier: Tier.vassal,
    type: [MonsterType.spellcaster, MonsterType.ancient],
    level: 2,
    toHit: 5,
    accuracy: 6,
    wounds: 10,
    atBonus: 1,
    exhibitionStartingWounds: 4,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
  }),
  Object.freeze({
    id: BOG_WITCH_ID,
    name: 'Bog Witch',
    tier: Tier.vassal,
    type: [MonsterType.spellcaster, MonsterType.ancient],
    level: 3,
    toHit: 7,
    accuracy: 7,
    wounds: 10,
    atBonus: 3,
    escalations: 1,
    vigorLossBonus: 4,
    exhibitionStartingWounds: 4,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
  }),
  Object.freeze({
    id: BOG_WITCH_ID,
    name: 'Bog Witch',
    tier: Tier.vassal,
    type: [MonsterType.spellcaster, MonsterType.ancient],
    level: 4,
    toHit: 9,
    accuracy: 10,
    wounds: 10,
    atBonus: 5,
    escalations: 2,
    vigorLossBonus: 2,
    exhibitionStartingWounds: 4,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
  }),
];

// Bog Witch stage patterns (20 stages)
// Pattern: '  111 222  333. 4444'
export const BOG_WITCH_STAGES = [
  null,
  null,
  1,
  1,
  1,
  null,
  2,
  2,
  2,
  null,
  null,
  3,
  3,
  3,
  null,
  null,
  4,
  4,
  4,
  4,
];
