import { MonsterType, Tier } from '@/catalogs/tier';
import { activationCounter, ActivationToken, MonsterStats } from '@/models/monster';

export const DEVIL_OF_THE_SMELTED_FEARS_ID = 'devil-of-the-smelted-fears';

export const devilOfTheSmeltedFears: ReadonlyArray<MonsterStats> = [
  Object.freeze({
    id: DEVIL_OF_THE_SMELTED_FEARS_ID,
    name: 'Devil of the Smelted Fears',
    tier: Tier.devil,
    type: [MonsterType.horror, MonsterType.cursed],
    level: 1,
    toHit: 7,
    accuracy: 9,
    wounds: 10,
    exhibitionStartingWounds: 3,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 1)],
    traits: [],
  }),
  Object.freeze({
    id: DEVIL_OF_THE_SMELTED_FEARS_ID,
    name: 'Devil of the Smelted Fears',
    level: 2,
    toHit: 8,
    accuracy: 10,
    tier: Tier.devil,
    type: [MonsterType.horror, MonsterType.cursed],
    wounds: 8,
    exhibitionStartingWounds: 2,
    aiActivation: [activationCounter(ActivationToken.standard, 2)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
    atBonus: 2,
    vigorLossBonus: 1,
  }),
  Object.freeze({
    id: DEVIL_OF_THE_SMELTED_FEARS_ID,
    name: 'Devil of the Smelted Fears',
    level: 3,
    toHit: 9,
    accuracy: 11,
    tier: Tier.devil,
    type: [MonsterType.horror, MonsterType.cursed],
    wounds: 8,
    exhibitionStartingWounds: 2,
    aiActivation: [activationCounter(ActivationToken.standard, 2)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
    atBonus: 3,
    vigorLossBonus: 2,
  }),
  Object.freeze({
    id: DEVIL_OF_THE_SMELTED_FEARS_ID,
    name: 'Devil of the Smelted Fears',
    level: 4,
    toHit: 9,
    accuracy: 12,
    tier: Tier.devil,
    type: [MonsterType.horror, MonsterType.cursed],
    wounds: 9,
    exhibitionStartingWounds: 2,
    aiActivation: [activationCounter(ActivationToken.standard, 2)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
    atBonus: 6,
    vigorLossBonus: 3,
    escalationBonus: 1,
  }),
];

// Devil of the Smelted Fears stage patterns (20 stages)
// Pattern: "           111222333"
export const DEVIL_OF_THE_SMELTED_FEARS_STAGES = [
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  1,
  1,
  1,
  2,
  2,
  2,
  3,
  3,
];
