import { activationCounter, ActivationToken, MonsterStats } from '@/models/monster';
import { MonsterType, Tier } from '../tier';

export const EGGKNIGHT_ID = 'eggknight';

export const eggknight: ReadonlyArray<MonsterStats> = [
  Object.freeze({
    id: EGGKNIGHT_ID,
    name: 'Eggknight',
    tier: Tier.vassal,
    type: [MonsterType.knight, MonsterType.egg],
    level: 1,
    toHit: 3,
    accuracy: 6,
    wounds: 8,
    exhibitionStartingWounds: 2,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
  }),
  Object.freeze({
    id: EGGKNIGHT_ID,
    name: 'Eggknight',
    tier: Tier.vassal,
    type: [MonsterType.knight, MonsterType.egg],
    level: 2,
    toHit: 5,
    accuracy: 7,
    wounds: 10,
    exhibitionStartingWounds: 4,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
    atBonus: 4,
    vigorLossBonus: 1,
    escalations: 1,
  }),
  Object.freeze({
    id: EGGKNIGHT_ID,
    name: 'Eggknight',
    tier: Tier.vassal,
    type: [MonsterType.knight, MonsterType.egg],
    level: 3,
    toHit: 7,
    accuracy: 9,
    wounds: 10,
    exhibitionStartingWounds: 4,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
    atBonus: 4,
    vigorLossBonus: 1,
    escalations: 1,
  }),
  Object.freeze({
    id: EGGKNIGHT_ID,
    name: 'Eggknight',
    tier: Tier.vassal,
    type: [MonsterType.knight, MonsterType.egg],
    level: 3,
    toHit: 9,
    accuracy: 11,
    wounds: 10,
    exhibitionStartingWounds: 4,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
    atBonus: 6,
    vigorLossBonus: 2,
    escalations: 1,
  }),
];

// Eggknight stage patterns (20 stages)
// Pattern: "111 222 333  444    "
export const EGGKNIGHT_STAGES = [
  1,
  1,
  1,
  null,
  2,
  2,
  2,
  null,
  3,
  3,
  3,
  null,
  null,
  4,
  4,
  4,
  null,
  null,
  null,
  null,
];
