import { activationCounter, ActivationToken, MonsterStats } from '@/models/monster';
import { MonsterType, Tier } from '../tier';

export const FIRST_MEN_WARRIORS_ID = 'first-men-warriors';

export const firstMenWarriors: ReadonlyArray<MonsterStats> = [
  Object.freeze({
    id: FIRST_MEN_WARRIORS_ID,
    name: 'First Men Warriors',
    tier: Tier.mob,
    type: [MonsterType.soldier, MonsterType.ape],
    level: 1,
    toHit: 2,
    accuracy: 6,
    wounds: 7,
    exhibitionStartingWounds: 1,
    aiActivation: [activationCounter(ActivationToken.standard, 2)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
  }),
  Object.freeze({
    id: FIRST_MEN_WARRIORS_ID,
    name: 'First Men Warriors',
    tier: Tier.mob,
    type: [MonsterType.soldier, MonsterType.ape],
    level: 2,
    toHit: 4,
    accuracy: 6,
    wounds: 8,
    exhibitionStartingWounds: 2,
    aiActivation: [activationCounter(ActivationToken.standard, 2)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
    atBonus: 2,
    vigorLossBonus: 1,
  }),
  Object.freeze({
    id: FIRST_MEN_WARRIORS_ID,
    name: 'First Men Warriors',
    tier: Tier.mob,
    type: [MonsterType.soldier, MonsterType.ape],
    level: 3,
    toHit: 5,
    accuracy: 8,
    wounds: 8,
    exhibitionStartingWounds: 2,
    aiActivation: [activationCounter(ActivationToken.standard, 2)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
    atBonus: 3,
    vigorLossBonus: 2,
  }),
  Object.freeze({
    id: FIRST_MEN_WARRIORS_ID,
    name: 'First Men Warriors',
    tier: Tier.mob,
    type: [MonsterType.soldier, MonsterType.ape],
    level: 4,
    toHit: 7,
    accuracy: 9,
    wounds: 9,
    exhibitionStartingWounds: 2,
    aiActivation: [activationCounter(ActivationToken.standard, 2)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
    atBonus: 6,
    vigorLossBonus: 3,
    escalationBonus: 1,
  }),
];

// First Men Warriors stage patterns (20 stages)
// Pattern: "11 222 333 444      "
export const FIRST_MEN_WARRIORS_STAGES = [
  1,
  1,
  null,
  2,
  2,
  2,
  null,
  3,
  3,
  3,
  null,
  4,
  4,
  4,
  null,
  null,
  null,
  null,
  null,
  null,
];
