import { activationCounter, ActivationToken, MonsterStats } from '@/models/monster';
import { MonsterType, Tier } from '../tier';

export const FIRST_MEN_LICTOR_HUNTERS_ID = 'first-men-lictor-hunters';

export const firstMenLictorHunters: ReadonlyArray<MonsterStats> = [
  Object.freeze({
    id: FIRST_MEN_LICTOR_HUNTERS_ID,
    name: 'First Men Lictor Hunters',
    tier: Tier.mob,
    type: [MonsterType.hunter, MonsterType.ape],
    level: 1,
    toHit: 3,
    accuracy: 6,
    wounds: 7,
    exhibitionStartingWounds: 1,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 1)],
    traits: [],
  }),
  Object.freeze({
    id: FIRST_MEN_LICTOR_HUNTERS_ID,
    name: 'First Men Lictor Hunters',
    tier: Tier.mob,
    type: [MonsterType.hunter, MonsterType.ape],
    level: 2,
    toHit: 4,
    accuracy: 7,
    wounds: 8,
    exhibitionStartingWounds: 2,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 1)],
    traits: [],
    atBonus: 1,
  }),
  Object.freeze({
    id: FIRST_MEN_LICTOR_HUNTERS_ID,
    name: 'First Men Lictor Hunters',
    tier: Tier.mob,
    type: [MonsterType.hunter, MonsterType.ape],
    level: 3,
    toHit: 6,
    accuracy: 9,
    wounds: 8,
    exhibitionStartingWounds: 2,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 1)],
    traits: [],
    atBonus: 3,
    vigorLossBonus: 1,
    escalations: 1,
  }),
  Object.freeze({
    id: FIRST_MEN_LICTOR_HUNTERS_ID,
    name: 'First Men Lictor Hunters',
    tier: Tier.mob,
    type: [MonsterType.hunter, MonsterType.ape],
    level: 4,
    toHit: 8,
    accuracy: 10,
    wounds: 9,
    exhibitionStartingWounds: 2,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 1)],
    traits: [],
    atBonus: 5,
    vigorLossBonus: 3,
    escalations: 2,
  }),
];

// First Men Lictor Hunters stage patterns (20 stages)
// Pattern: "111222 333  444     "
export const FIRST_MEN_LICTOR_HUNTERS_STAGES = [
  1,
  1,
  1,
  2,
  2,
  2,
  null,
  3,
  3,
  3,
  null,
  null,
  4,
  4,
  4,
  null,
  null,
  null,
  null,
  null,
];
