import { activationCounter, ActivationToken, MonsterStats } from '@/models/monster';
import { MonsterType, Tier } from '../tier';

export const HAUNTS_OF_UTREBANT_ID = 'haunts-of-utrebant';

export const hauntsOfUtrebant: ReadonlyArray<MonsterStats> = [
  Object.freeze({
    id: HAUNTS_OF_UTREBANT_ID,
    name: 'Haunts of Utrebant',
    tier: Tier.mob,
    type: [MonsterType.undead, MonsterType.ancient],
    level: 1,
    toHit: 3,
    accuracy: 7,
    wounds: 7,
    exhibitionStartingWounds: 1,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 1)],
    traits: [],
  }),
  Object.freeze({
    id: HAUNTS_OF_UTREBANT_ID,
    name: 'Haunts of Utrebant',
    tier: Tier.mob,
    type: [MonsterType.undead, MonsterType.ancient],
    level: 2,
    toHit: 5,
    accuracy: 9,
    wounds: 8,
    exhibitionStartingWounds: 2,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 1)],
    traits: [],
    atBonus: 2,
  }),
  Object.freeze({
    id: HAUNTS_OF_UTREBANT_ID,
    name: 'Haunts of Utrebant',
    tier: Tier.mob,
    type: [MonsterType.undead, MonsterType.ancient],
    level: 3,
    toHit: 7,
    accuracy: 9,
    wounds: 8,
    exhibitionStartingWounds: 2,
    aiActivation: [activationCounter(ActivationToken.standard, 2)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
    atBonus: 3,
    escalationBonus: 1,
  }),
  Object.freeze({
    id: HAUNTS_OF_UTREBANT_ID,
    name: 'Haunts of Utrebant',
    tier: Tier.mob,
    type: [MonsterType.undead, MonsterType.ancient],
    level: 4,
    toHit: 9,
    accuracy: 10,
    wounds: 9,
    exhibitionStartingWounds: 2,
    aiActivation: [activationCounter(ActivationToken.standard, 2)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
    atBonus: 5,
    escalationBonus: 2,
  }),
];

// Haunts of Utrebant stage patterns (20 stages)
// Pattern: " 111 222 333 444    "
export const HAUNTS_OF_UTREBANT_STAGES = [
  null,
  1,
  1,
  1,
  null,
  2,
  2,
  2,
  null,
  3,
  3,
  3,
  null,
  4,
  4,
  4,
  null,
  null,
  null,
  null,
];
