import { activationCounter, ActivationToken, MonsterStats } from '@/models/monster';
import { MonsterType, Tier } from '../tier';

export const IRONCAST_DEAD_ID = 'ironcast-dead';

export const ironcastDead: ReadonlyArray<MonsterStats> = [
  Object.freeze({
    id: IRONCAST_DEAD_ID,
    name: 'Ironcast Dead',
    tier: Tier.mob,
    type: [MonsterType.machinated, MonsterType.undead, MonsterType.soldier],
    level: 1,
    toHit: 2,
    accuracy: 5,
    wounds: 7,
    exhibitionStartingWounds: 1,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 1)],
    traits: [],
  }),
  Object.freeze({
    id: IRONCAST_DEAD_ID,
    name: 'Ironcast Dead',
    tier: Tier.mob,
    type: [MonsterType.machinated, MonsterType.undead, MonsterType.soldier],
    level: 2,
    toHit: 3,
    accuracy: 6,
    wounds: 8,
    exhibitionStartingWounds: 2,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 1)],
    traits: [],
    atBonus: 1,
    vigorLossBonus: 1,
  }),
  Object.freeze({
    id: IRONCAST_DEAD_ID,
    name: 'Ironcast Dead',
    tier: Tier.mob,
    type: [MonsterType.machinated, MonsterType.undead, MonsterType.soldier],
    level: 3,
    toHit: 4,
    accuracy: 8,
    wounds: 8,
    exhibitionStartingWounds: 2,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 1)],
    traits: [],
    atBonus: 2,
    vigorLossBonus: 3,
    escalationBonus: 1,
  }),
  Object.freeze({
    id: IRONCAST_DEAD_ID,
    name: 'Ironcast Dead',
    tier: Tier.mob,
    type: [MonsterType.machinated, MonsterType.undead, MonsterType.soldier],
    level: 4,
    toHit: 5,
    accuracy: 9,
    wounds: 8,
    exhibitionStartingWounds: 2,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 1)],
    traits: [],
    atBonus: 3,
    vigorLossBonus: 6,
    escalationBonus: 1,
  }),
];

// Ironcast Dead stage patterns (20 stages)
// Pattern: "111 222 333 444      "
export const IRONCAST_DEAD_STAGES = [
  1,
  1,
  1,
  null,
  2,
  2,
  2,
  null,
  3,
  3,
  3,
  null,
  4,
  4,
  4,
  null,
  null,
  null,
  null,
  null,
];
