import { activationCounter, ActivationToken, MonsterStats } from '@/models/monster';
import { MonsterType, Tier } from '../tier';

export const KING_LAID_LOW_ID = 'king-laid-low';

export const kingLaidLow: ReadonlyArray<MonsterStats> = [
  Object.freeze({
    id: KING_LAID_LOW_ID,
    name: 'King Laid Low',
    tier: Tier.king,
    type: [MonsterType.beast, MonsterType.cursed],
    level: 1,
    toHit: 6,
    accuracy: 8,
    wounds: 10,
    exhibitionStartingWounds: 3,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 1)],
    traits: [],
    escalationBonus: 1,
  }),
  Object.freeze({
    id: KING_LAID_LOW_ID,
    name: 'King Laid Low',
    tier: Tier.king,
    type: [MonsterType.beast, MonsterType.cursed],
    level: 2,
    toHit: 7,
    accuracy: 9,
    wounds: 10,
    exhibitionStartingWounds: 3,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 1)],
    traits: [],
    escalationBonus: 1,
    atBonus: 1,
    vigorLossBonus: 1,
  }),
  Object.freeze({
    id: KING_LAID_LOW_ID,
    name: 'King Laid Low',
    tier: Tier.king,
    type: [MonsterType.beast, MonsterType.cursed],
    level: 3,
    toHit: 8,
    accuracy: 10,
    wounds: 10,
    exhibitionStartingWounds: 8,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 1)],
    traits: [],
    escalationBonus: 1,
    atBonus: 2,
    vigorLossBonus: 1,
  }),
  Object.freeze({
    id: KING_LAID_LOW_ID,
    name: 'King Laid Low',
    tier: Tier.king,
    type: [MonsterType.beast, MonsterType.cursed],
    level: 4,
    toHit: 9,
    accuracy: 10,
    wounds: 10,
    exhibitionStartingWounds: 3,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 1)],
    traits: [],
    escalationBonus: 2,
    atBonus: 3,
    vigorLossBonus: 2,
    evasionDiceBonus: 1,
  }),
];

// King Laid Low stage patterns (20 stages)
// Pattern: "       1112223334444"
export const KING_LAID_LOW_STAGES = [
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  1,
  1,
  1,
  2,
  2,
  2,
  3,
  3,
  3,
  4,
  4,
  4,
];
