import { activationCounter, ActivationToken, MonsterStats } from '@/models/monster';

export const KNIGHT_OF_THE_FEN_ID = 'knight-of-the-fen';

export const knightOfTheFen: ReadonlyArray<MonsterStats> = [
  Object.freeze({
    id: KNIGHT_OF_THE_FEN_ID,
    name: 'Knight of the Fen',
    level: 1,
    toHit: 4,
    accuracy: 6,
    wounds: 8,
    exhibitionStartingWounds: 2,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
  }),
  Object.freeze({
    id: KNIGHT_OF_THE_FEN_ID,
    name: 'Knight of the Fen',
    level: 2,
    toHit: 6,
    accuracy: 8,
    wounds: 10,
    exhibitionStartingWounds: 4,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
    atBonus: 2,
    vigorLossBonus: 1,
  }),
  Object.freeze({
    id: KNIGHT_OF_THE_FEN_ID,
    name: 'Knight of the Fen',
    level: 3,
    toHit: 7,
    accuracy: 9,
    wounds: 10,
    exhibitionStartingWounds: 4,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
    atBonus: 3,
    vigorLossBonus: 2,
    escalationBonus: 1,
  }),
  Object.freeze({
    id: KNIGHT_OF_THE_FEN_ID,
    name: 'Knight of the Fen',
    level: 4,
    toHit: 8,
    accuracy: 11,
    wounds: 10,
    exhibitionStartingWounds: 4,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
    atBonus: 4,
    vigorLossBonus: 4,
    escalationBonus: 2,
  }),
];

// Knight of the Fen stage patterns (20 stages)
// Pattern: " 111  222 333  44444"
export const KNIGHT_OF_THE_FEN_STAGES = [
  null,
  1,
  1,
  1,
  null,
  null,
  2,
  2,
  2,
  null,
  3,
  3,
  3,
  null,
  null,
  4,
  4,
  4,
  4,
  4,
];
