import { activationCounter, ActivationToken, MonsterStats } from '@/models/monster';
import { MonsterType, Tier } from '../tier';

export const KNIGHTEATER_ID = 'knighteater';

export const knighteater: ReadonlyArray<MonsterStats> = [
  Object.freeze({
    id: KNIGHTEATER_ID,
    name: 'Knighteater',
    tier: Tier.vassal,
    type: [MonsterType.hunger, MonsterType.knight, MonsterType.hunter],
    level: 1,
    toHit: 4,
    accuracy: 5,
    wounds: 8,
    exhibitionStartingWounds: 2,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
  }),
  Object.freeze({
    id: KNIGHTEATER_ID,
    name: 'Knighteater',
    tier: Tier.vassal,
    type: [MonsterType.hunger, MonsterType.knight, MonsterType.hunter],
    level: 2,
    toHit: 6,
    accuracy: 6,
    wounds: 10,
    exhibitionStartingWounds: 4,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
    atBonus: 2,
    vigorLossBonus: 1,
    escalationBonus: 1,
  }),
  Object.freeze({
    id: KNIGHTEATER_ID,
    name: 'Knighteater',
    tier: Tier.vassal,
    type: [MonsterType.hunger, MonsterType.knight, MonsterType.hunter],
    level: 3,
    toHit: 8,
    accuracy: 7,
    wounds: 10,
    exhibitionStartingWounds: 4,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
    atBonus: 4,
    vigorLossBonus: 2,
    escalationBonus: 1,
  }),
  Object.freeze({
    id: KNIGHTEATER_ID,
    name: 'Knighteater',
    tier: Tier.vassal,
    type: [MonsterType.hunger, MonsterType.knight, MonsterType.hunter],
    level: 4,
    toHit: 10,
    accuracy: 8,
    wounds: 10,
    exhibitionStartingWounds: 4,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
    atBonus: 6,
    vigorLossBonus: 3,
    escalationBonus: 2,
  }),
];

// Knighteater stage patterns (20 stages)
// Pattern: '. 111 222. 333. 4444'
export const KNIGHTEATER_STAGES = [
  null,
  null,
  1,
  1,
  1,
  null,
  2,
  2,
  2,
  null,
  null,
  3,
  3,
  3,
  null,
  null,
  4,
  4,
  4,
  4,
];
