import { activationCounter, ActivationToken, MonsterStats } from '@/models/monster';
import { MonsterType, Tier } from '../tier';

export const PALEBLOOD_WORM_ID = 'paleblood-worms';

export const palebloodWorms: ReadonlyArray<MonsterStats> = [
  Object.freeze({
    id: PALEBLOOD_WORM_ID,
    name: 'Paleblood Worms',
    tier: Tier.mob,
    type: [MonsterType.parasite, MonsterType.parasite, MonsterType.blood],
    level: 1,
    toHit: 3,
    accuracy: 6,
    wounds: 7,
    exhibitionStartingWounds: 1,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 1)],
    traits: [],
  }),
  Object.freeze({
    id: PALEBLOOD_WORM_ID,
    name: 'Paleblood Worms',
    tier: Tier.mob,
    type: [MonsterType.parasite, MonsterType.parasite, MonsterType.blood],
    level: 2,
    toHit: 4,
    accuracy: 8,
    wounds: 8,
    exhibitionStartingWounds: 2,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 1)],
    traits: [],
    atBonus: 1,
    vigorLossBonus: 1,
  }),
  Object.freeze({
    id: PALEBLOOD_WORM_ID,
    name: 'Paleblood Worms',
    tier: Tier.mob,
    type: [MonsterType.parasite, MonsterType.parasite, MonsterType.blood],
    level: 3,
    toHit: 5,
    accuracy: 9,
    wounds: 8,
    exhibitionStartingWounds: 2,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 1)],
    traits: [],
    atBonus: 1,
    vigorLossBonus: 2,
    escalationBonus: 1,
  }),
  Object.freeze({
    id: PALEBLOOD_WORM_ID,
    name: 'Paleblood Worms',
    tier: Tier.mob,
    type: [MonsterType.parasite, MonsterType.parasite, MonsterType.blood],
    level: 4,
    toHit: 7,
    accuracy: 10,
    wounds: 8,
    exhibitionStartingWounds: 2,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 1)],
    traits: [],
    atBonus: 3,
    vigorLossBonus: 3,
    escalationBonus: 1,
  }),
];

// Paleblood Worms stage patterns (20 stages)
// Pattern: "111222 333  444     "
export const PALEBLOOD_WORMS_STAGES = [
  1,
  1,
  1,
  2,
  2,
  2,
  null,
  3,
  3,
  3,
  null,
  null,
  4,
  4,
  4,
  null,
  null,
  null,
  null,
  null,
];
