import { activationCounter, ActivationToken, MonsterStats } from '@/models/monster';
import { MonsterType, Tier } from '../tier';

export const PANZERGEIST_ID = 'panzergeist';

export const panzergeist: ReadonlyArray<MonsterStats> = [
  Object.freeze({
    id: PANZERGEIST_ID,
    name: 'Panzergeist',
    tier: Tier.mob,
    type: [MonsterType.undead, MonsterType.knight],
    level: 1,
    toHit: 3,
    accuracy: 6,
    wounds: 7,
    exhibitionStartingWounds: 1,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 1)],
    traits: [],
  }),
  Object.freeze({
    id: PANZERGEIST_ID,
    name: 'Panzergeist',
    tier: Tier.mob,
    type: [MonsterType.undead, MonsterType.knight],
    level: 2,
    toHit: 5,
    accuracy: 7,
    wounds: 8,
    exhibitionStartingWounds: 2,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 1)],
    traits: [],
    atBonus: 2,
  }),
  Object.freeze({
    id: PANZERGEIST_ID,
    name: 'Panzergeist',
    tier: Tier.mob,
    type: [MonsterType.undead, MonsterType.knight],
    level: 3,
    toHit: 6,
    accuracy: 9,
    wounds: 8,
    exhibitionStartingWounds: 2,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 1)],
    traits: [],
    atBonus: 3,
    vigorLossBonus: 1,
  }),
  Object.freeze({
    id: PANZERGEIST_ID,
    name: 'Panzergeist',
    tier: Tier.mob,
    type: [MonsterType.undead, MonsterType.knight],
    level: 4,
    toHit: 7,
    accuracy: 10,
    wounds: 8,
    exhibitionStartingWounds: 2,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 1)],
    traits: [],
    atBonus: 4,
    vigorLossBonus: 3,
    escalationBonus: 1,
  }),
];

// Panzergeist stage patterns (20 stages)
// Pattern: '111 222 333 444     '
export const PANZERGEIST_STAGES = [
  1,
  1,
  1,
  null,
  2,
  2,
  2,
  null,
  3,
  3,
  3,
  null,
  4,
  4,
  4,
  null,
  null,
  null,
  null,
  null,
];
