import { activationCounter, ActivationToken, MonsterStats } from '@/models/monster';
import { MonsterType, Tier } from '../tier';

export const PUMPKINHEAD_MONSTROSITIES_ID = 'pumpkinhead-monstrosities';

export const pumpkinheadMonstrosities: ReadonlyArray<MonsterStats> = [
  Object.freeze({
    id: PUMPKINHEAD_MONSTROSITIES_ID,
    name: 'Pumpkinhead Monstrosities',
    tier: Tier.mob,
    type: [MonsterType.plant, MonsterType.beast],
    level: 1,
    toHit: 3,
    accuracy: 6,
    wounds: 5,
    exhibitionStartingWounds: 1,
    aiActivation: [activationCounter(ActivationToken.standard, 2)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
  }),
  Object.freeze({
    id: PUMPKINHEAD_MONSTROSITIES_ID,
    name: 'Pumpkinhead Monstrosities',
    tier: Tier.mob,
    type: [MonsterType.plant, MonsterType.beast],
    level: 2,
    toHit: 5,
    accuracy: 7,
    wounds: 6,
    exhibitionStartingWounds: 2,
    aiActivation: [activationCounter(ActivationToken.standard, 2)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
    atBonus: 3,
    vigorLossBonus: 1,
  }),
  Object.freeze({
    id: PUMPKINHEAD_MONSTROSITIES_ID,
    name: 'Pumpkinhead Monstrosities',
    tier: Tier.mob,
    type: [MonsterType.plant, MonsterType.beast],
    level: 3,
    toHit: 7,
    accuracy: 8,
    wounds: 6,
    exhibitionStartingWounds: 2,
    aiActivation: [activationCounter(ActivationToken.standard, 2)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
    atBonus: 5,
    vigorLossBonus: 3,
  }),
  Object.freeze({
    id: PUMPKINHEAD_MONSTROSITIES_ID,
    name: 'Pumpkinhead Monstrosities',
    tier: Tier.mob,
    type: [MonsterType.plant, MonsterType.beast],
    level: 4,
    toHit: 5,
    accuracy: 9,
    wounds: 6,
    exhibitionStartingWounds: 2,
    aiActivation: [activationCounter(ActivationToken.standard, 2)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
    atBonus: 6,
    vigorLossBonus: 5,
  }),
];

// Pumpkinhead Monstrosities stage patterns (20 stages)
// Pattern: "111 222 333 444     "
export const PUMPKINHEAD_MONSTROSITIES_STAGES = [
  1,
  1,
  1,
  null,
  2,
  2,
  2,
  null,
  3,
  3,
  3,
  null,
  4,
  4,
  4,
  null,
  null,
  null,
  null,
  null,
];
