import { activationCounter, ActivationToken, MonsterStats } from '@/models/monster';
import { MonsterType, Tier } from '../tier';

export const PUPPET_KING_EDELHARDT_ID = 'puppet-king-edelhardt';

export const puppetKingEdelhardt: ReadonlyArray<MonsterStats> = [
  Object.freeze({
    id: PUPPET_KING_EDELHARDT_ID,
    name: 'Puppet King Edelhardt',
    tier: Tier.king,
    type: [MonsterType.parasite, MonsterType.undead],
    level: 1,
    toHit: 6,
    accuracy: 7,
    wounds: 10,
    exhibitionStartingWounds: 3,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 1)],
    traits: [],
  }),
  Object.freeze({
    id: PUPPET_KING_EDELHARDT_ID,
    name: 'Puppet King Edelhardt',
    tier: Tier.king,
    type: [MonsterType.parasite, MonsterType.undead],
    level: 2,
    toHit: 7,
    accuracy: 7,
    wounds: 10,
    exhibitionStartingWounds: 3,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 1)],
    traits: [],
    atBonus: 1,
    vigorLossBonus: 1,
    escalationBonus: 1,
  }),
  Object.freeze({
    id: PUPPET_KING_EDELHARDT_ID,
    name: 'Puppet King Edelhardt',
    tier: Tier.king,
    type: [MonsterType.parasite, MonsterType.undead],
    level: 3,
    toHit: 8,
    accuracy: 8,
    wounds: 10,
    exhibitionStartingWounds: 3,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 1)],
    traits: [],
    atBonus: 2,
    vigorLossBonus: 1,
    escalationBonus: 1,
    evasionDiceBonus: 1,
  }),
  Object.freeze({
    id: PUPPET_KING_EDELHARDT_ID,
    name: 'Puppet King Edelhardt',
    tier: Tier.king,
    type: [MonsterType.parasite, MonsterType.undead],
    level: 4,
    toHit: 10,
    accuracy: 9,
    wounds: 10,
    exhibitionStartingWounds: 3,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 1)],
    traits: [],
    atBonus: 4,
    vigorLossBonus: 2,
    escalationBonus: 2,
    evasionDiceBonus: 2,
  }),
];

// Puppet King Edelhardt stage patterns (20 stages)
// Pattern: "       1112223334444"
export const PUPPET_KING_EDELHARDT_STAGES = [
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  1,
  1,
  1,
  2,
  2,
  2,
  3,
  3,
  3,
  4,
  4,
  4,
];
