import { activationCounter, ActivationToken, MonsterStats } from '@/models/monster';
import { Frenzy, PackHunters } from '../traits';

export const RATWOLVES_ID = 'ratwolves';

export const ratwolves: ReadonlyArray<MonsterStats> = [
  Object.freeze({
    id: RATWOLVES_ID,
    name: 'Ratwolves',
    level: 1,
    toHit: 2,
    accuracy: 6,
    wounds: 4,
    exhibitionStartingWounds: 1,
    aiActivation: [activationCounter(ActivationToken.standard, 2)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [PackHunters, Frenzy],
  }),
  Object.freeze({
    id: RATWOLVES_ID,
    name: 'Ratwolves',
    level: 2,
    accuracy: 6,
    toHit: 3,
    wounds: 5,
    exhibitionStartingWounds: 2,
    aiActivation: [activationCounter(ActivationToken.standard, 2)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    atBonus: 1,
    vigorLossBonus: 1,
    traits: [PackHunters, Frenzy],
  }),
  Object.freeze({
    id: RATWOLVES_ID,
    name: 'Ratwolves',
    level: 3,
    toHit: 4,
    wounds: 5,
    accuracy: 7,
    exhibitionStartingWounds: 2,
    aiActivation: [activationCounter(ActivationToken.standard, 2)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    atBonus: 2,
    vigorLossBonus: 1,
    escalations: 1,
    traits: [PackHunters, Frenzy],
  }),
  Object.freeze({
    id: RATWOLVES_ID,
    name: 'Ratwolves',
    level: 4,
    toHit: 4,
    wounds: 5,
    accuracy: 8,
    exhibitionStartingWounds: 2,
    aiActivation: [activationCounter(ActivationToken.standard, 2)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    atBonus: 3,
    vigorLossBonus: 2,
    evasionDiceBonus: 1,
    escalations: 1,
    traits: [PackHunters, Frenzy],
  }),
];

// Ratwolves stage patterns (20 stages)
// Pattern: "11222 333444        "
export const RATWOLVES_STAGES = [
  1,
  1,
  2,
  2,
  2,
  null,
  3,
  3,
  3,
  4,
  4,
  4,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
];
