import { activationCounter, ActivationToken, MonsterStats } from '@/models/monster';
import { MonsterType, Tier } from '../tier';

export const STONEMASON_KNIGHT_ID = 'stonemasonknight';

export const stonemasonKnight: ReadonlyArray<MonsterStats> = [
  Object.freeze({
    id: STONEMASON_KNIGHT_ID,
    name: 'Stonemason Knight',
    tier: Tier.vassal,
    type: [MonsterType.construct, MonsterType.knight, MonsterType.stone],
    level: 1,
    toHit: 4,
    accuracy: 6,
    wounds: 8,
    exhibitionStartingWounds: 2,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
  }),
  Object.freeze({
    id: STONEMASON_KNIGHT_ID,
    name: 'Stonemason Knight',
    tier: Tier.vassal,
    type: [MonsterType.construct, MonsterType.knight, MonsterType.stone],
    level: 2,
    toHit: 5,
    accuracy: 7,
    wounds: 10,
    exhibitionStartingWounds: 4,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
    atBonus: 1,
    vigorLossBonus: 2,
  }),
  Object.freeze({
    id: STONEMASON_KNIGHT_ID,
    name: 'Stonemason Knight',
    tier: Tier.vassal,
    type: [MonsterType.construct, MonsterType.knight, MonsterType.stone],
    level: 3,
    toHit: 6,
    accuracy: 8,
    wounds: 10,
    exhibitionStartingWounds: 4,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
    atBonus: 2,
    vigorLossBonus: 3,
    escalationBonus: 1,
  }),
  Object.freeze({
    id: STONEMASON_KNIGHT_ID,
    name: 'Stonemason Knight',
    tier: Tier.vassal,
    type: [MonsterType.construct, MonsterType.knight, MonsterType.stone],
    level: 4,
    toHit: 7,
    accuracy: 10,
    wounds: 10,
    exhibitionStartingWounds: 4,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
    atBonus: 3,
    vigorLossBonus: 6,
    escalationBonus: 1,
  }),
];

// Stonemason Knight stage patterns (20 stages)
// Pattern: " 111 222  333  44444"
export const STONEMASON_KNIGHT_STAGES = [
  null,
  1,
  1,
  1,
  null,
  2,
  2,
  2,
  null,
  null,
  3,
  3,
  3,
  null,
  null,
  4,
  4,
  4,
  4,
  4,
];
