import { activationCounter, ActivationToken, MonsterStats } from '@/models/monster';
import { MonsterType, Tier } from '../tier';

export const WHITE_APE_TROLL_ID = 'white-ape-troll';

export const whiteApeTroll: ReadonlyArray<MonsterStats> = [
  Object.freeze({
    id: WHITE_APE_TROLL_ID,
    name: 'White Ape Troll',
    tier: Tier.vassal,
    type: [MonsterType.ape, MonsterType.beast],
    level: 1,
    toHit: 3,
    accuracy: 6,
    wounds: 6,
    exhibitionStartingWounds: 1,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
  }),
  Object.freeze({
    id: WHITE_APE_TROLL_ID,
    name: 'White Ape Troll',
    tier: Tier.vassal,
    type: [MonsterType.ape, MonsterType.beast],
    level: 2,
    toHit: 5,
    accuracy: 7,
    wounds: 8,
    exhibitionStartingWounds: 3,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
    atBonus: 2,
    vigorLossBonus: 1,
  }),
  Object.freeze({
    id: WHITE_APE_TROLL_ID,
    name: 'White Ape Troll',
    tier: Tier.vassal,
    type: [MonsterType.ape, MonsterType.beast],
    level: 3,
    toHit: 6,
    accuracy: 8,
    wounds: 8,
    exhibitionStartingWounds: 3,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
    atBonus: 3,
    vigorLossBonus: 2,
  }),
  Object.freeze({
    id: WHITE_APE_TROLL_ID,
    name: 'White Ape Troll',
    tier: Tier.vassal,
    type: [MonsterType.ape, MonsterType.beast],
    level: 4,
    toHit: 9,
    accuracy: 8,
    wounds: 8,
    exhibitionStartingWounds: 3,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
    atBonus: 6,
    vigorLossBonus: 4,
    escalationBonus: 1,
  }),
];

// White Ape Troll stage patterns (20 stages)
// Pattern: "111 222 333  444    "
export const WHITE_APE_TROLL_STAGES = [
  1,
  1,
  1,
  null,
  2,
  2,
  2,
  null,
  3,
  3,
  3,
  null,
  null,
  4,
  4,
  4,
  null,
  null,
  null,
  null,
];
