import { activationCounter, ActivationToken, MonsterStats } from '@/models/monster';
import { MonsterType, Tier } from '../tier';

export const WINGED_NIGHTMARE_ID = 'winged-nightmare';

export const wingedNightmare: ReadonlyArray<MonsterStats> = [
  Object.freeze({
    id: WINGED_NIGHTMARE_ID,
    name: 'Winged Nightmare',
    tier: Tier.mob,
    type: [MonsterType.beast, MonsterType.horror],
    level: 1,
    toHit: 4,
    accuracy: 7,
    wounds: 6,
    exhibitionStartingWounds: 0,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
  }),
  Object.freeze({
    id: WINGED_NIGHTMARE_ID,
    name: 'Winged Nightmare',
    tier: Tier.mob,
    type: [MonsterType.beast, MonsterType.horror],
    level: 2,
    toHit: 5,
    accuracy: 9,
    wounds: 6,
    exhibitionStartingWounds: 0,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
    atBonus: 1,
    vigorLossBonus: 1,
  }),
  Object.freeze({
    id: WINGED_NIGHTMARE_ID,
    name: 'Winged Nightmare',
    tier: Tier.mob,
    type: [MonsterType.beast, MonsterType.horror],
    level: 3,
    toHit: 7,
    accuracy: 10,
    wounds: 6,
    exhibitionStartingWounds: 0,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
    atBonus: 3,
    vigorLossBonus: 2,
    escalationBonus: 1,
  }),
  Object.freeze({
    id: WINGED_NIGHTMARE_ID,
    name: 'Winged Nightmare',
    tier: Tier.mob,
    type: [MonsterType.beast, MonsterType.horror],
    level: 4,
    toHit: 9,
    accuracy: 12,
    wounds: 6,
    exhibitionStartingWounds: 0,
    aiActivation: [activationCounter(ActivationToken.standard, 1)],
    signatureActivation: [activationCounter(ActivationToken.signature, 0)],
    traits: [],
    atBonus: 5,
    vigorLossBonus: 3,
    escalationBonus: 1,
    evasionDiceBonus: 1,
  }),
];

// Winged Nightmare stage patterns (20 stages)
// Pattern: "  111222 333  444444"
export const WINGED_NIGHTMARE_STAGES = [
  null,
  null,
  1,
  1,
  1,
  2,
  2,
  2,
  null,
  3,
  3,
  3,
  null,
  null,
  4,
  4,
  4,
  4,
  4,
  4,
];
